server:
  port: 8088

spring:
  application:
    name: auth-service

jwt:
  secret: fitting-secret-key-2026-microservices-tienda-ropa-muy-larga
  expiration-ms: 86400000   # 24 horas en milisegundos

user:
  service:
    url: http://localhost:8087

logging:
  level:
    com.fitting.authservice: DEBUG